### ISSUE TITLE
按照步骤操作，应该是没有登录成功

### ISSUE THREAD

**Issue by yuxfeng275** [Pineapple666/TaobaoSpider#1]
![image](https://user-images.githubusercontent.com/13724705/91517223-e4329680-e91f-11ea-9505-bcf496379071.png)

**Comment by yuxfeng275** [comment]
保存了返回页面
![image](https://user-images.githubusercontent.com/13724705/91517301-04faec00-e920-11ea-8646-b770cb4a3d86.png)
还是淘宝的登录页面，不知道问题出在哪里？

**Comment by Pineapple666** [comment]
很高兴我的代码有人可以看到，也很高兴有人提出问题。我刚才测试了一下，是没有问题的
![图片](https://user-images.githubusercontent.com/62491424/91517926-96b72900-e921-11ea-9309-fbe86430f577.png)
你再检查一下那三个参数吧，要讨论的话加我QQ1836811530

**Comment by james-wangx** [comment]
很高兴能收到问题，我刚才又把代码下载了测试了一下，没有问题啊
![图片](https://user-images.githubusercontent.com/62491424/91518413-c7e42900-e922-11ea-8d37-c9f8ed4997bb.png)
你再检查一下那三个参数吧，还有问题讨论的话加我QQ1836811530

**Comment by yuxfeng275** [comment]
加你QQ了，我找到我这边不行的原因了
