### ISSUE TITLE
大佬有爬详情页的思路吗

### ISSUE THREAD

**Issue by LYY1121** [Pineapple666/TaobaoSpider#2]
感谢大佬的登录思路，我最近卡在爬淘宝详情页上了，爬页面上的价格倒是简单，但是折扣价和月销量这些都是另外请求返回的，直接复制cookie和参数发送请求都返回403，请大佬指点迷津

**Comment by james-wangx** [comment]
详情页面的抓取还是要依靠代理池和cookies池，因为淘宝的反爬太强了。之前试过连续请求详情页面导致直接封ip，用浏览器都打不开。具体的详情页面这种大规模的抓取，用这一套肯定是不行的。我这个代码是为之后换成Scrapy框架做铺垫的，等我研究好Scrapy再开始搞这个淘宝。

**Comment by LYY1121** [comment]
自动回复：     您好！我已收到您的来信！
